### ISSUE TITLE
Vue3 support?

### ISSUE THREAD

**Issue by ilmoi** [mathieustan/vue-intercom#1]
I couldn't get it working with Vue3. Any advice? Otherwise, when might we expect an upgrade that supports Vue3?

**Comment by mathieustan** [comment]
I really don't know. I have a lot of work these days.
I'll let you know.

**Comment by tbordinat** [comment]
Same question here. Did someone find a way, or eventually an alternative ?

**Comment by seunafara** [comment]
Anything yet guys??

**Comment by icontrerasn** [comment]
Any luck with this?

**Comment by deanmikan** [comment]
Bumping this but I assume not maintained for V3.

**Comment by miguel-andrade-nstart** [comment]
bumpy bump

**Comment by mreduar** [comment]
It is abandoned. It is time to look for alternatives. Any suggestions?

**Comment by mathieustan** [comment]
new release for vue3 : [release v1.0.0-alpha.0](https://github.com/mathieustan/vue-intercom/releases/tag/%40mathieustan%2Fvue-intercom%401.0.0-alpha.0)

**Comment by miguel-andrade-nstart** [comment]
oh wow!!!! that's awesome Mathieu, thanks a lot!
