### ISSUE TITLE
Update Intercom api to include newer methods

### ISSUE THREAD

**Issue by umerDev** [mathieustan/vue-intercom#3]
Allow users to update the Intercom API.

How would one update this file dist/vue-intercom.umd.js, where is this generated from.

Would updating this allow users to try functionality such as Intercom(‘showArticle’, 123); by doing 
$intercom.showArticle(articleNumber) ?

**Comment by mathieustan** [comment]
It is available in latest release for vue3. 
If you are still using vue2, you can easily use @mathieustan/intercom [as a service.](https://github.com/mathieustan/vue-intercom/tree/vue3?tab=readme-ov-file#service)
